server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/debug
    username: debug
    password: debug
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db-changelog/db-changelog.yml

  data:
    mongodb:
      authentication-database: admin
      username: debug
      password: debug
      database: admin
      port: 27017
      host: localhost
      auto-index-creation: true